/*
 * This file is generated by jOOQ.
 */
package io.github.rogerfilipes.infrastructure.repository.jooq.tables.records;


import io.github.rogerfilipes.infrastructure.repository.jooq.tables.Articles;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticlesRecord extends UpdatableRecordImpl<ArticlesRecord> implements Record8<UUID, String, String, String, String, UUID, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.articles.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.articles.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.articles.slug</code>.
     */
    public void setSlug(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.articles.slug</code>.
     */
    public String getSlug() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.articles.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.articles.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.articles.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.articles.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.articles.body</code>.
     */
    public void setBody(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.articles.body</code>.
     */
    public String getBody() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.articles.author</code>.
     */
    public void setAuthor(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.articles.author</code>.
     */
    public UUID getAuthor() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.articles.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.articles.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.articles.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.articles.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, String, String, String, String, UUID, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, String, String, String, String, UUID, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Articles.ARTICLES.ID;
    }

    @Override
    public Field<String> field2() {
        return Articles.ARTICLES.SLUG;
    }

    @Override
    public Field<String> field3() {
        return Articles.ARTICLES.TITLE;
    }

    @Override
    public Field<String> field4() {
        return Articles.ARTICLES.DESCRIPTION;
    }

    @Override
    public Field<String> field5() {
        return Articles.ARTICLES.BODY;
    }

    @Override
    public Field<UUID> field6() {
        return Articles.ARTICLES.AUTHOR;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Articles.ARTICLES.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Articles.ARTICLES.UPDATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSlug();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public String component5() {
        return getBody();
    }

    @Override
    public UUID component6() {
        return getAuthor();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSlug();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public String value5() {
        return getBody();
    }

    @Override
    public UUID value6() {
        return getAuthor();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdatedAt();
    }

    @Override
    public ArticlesRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ArticlesRecord value2(String value) {
        setSlug(value);
        return this;
    }

    @Override
    public ArticlesRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ArticlesRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ArticlesRecord value5(String value) {
        setBody(value);
        return this;
    }

    @Override
    public ArticlesRecord value6(UUID value) {
        setAuthor(value);
        return this;
    }

    @Override
    public ArticlesRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ArticlesRecord value8(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public ArticlesRecord values(UUID value1, String value2, String value3, String value4, String value5, UUID value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticlesRecord
     */
    public ArticlesRecord() {
        super(Articles.ARTICLES);
    }

    /**
     * Create a detached, initialised ArticlesRecord
     */
    public ArticlesRecord(UUID id, String slug, String title, String description, String body, UUID author, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Articles.ARTICLES);

        setId(id);
        setSlug(slug);
        setTitle(title);
        setDescription(description);
        setBody(body);
        setAuthor(author);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
