/*
 * This file is generated by jOOQ.
 */
package io.github.rogerfilipes.infrastructure.repository.jooq.tables.records;


import io.github.rogerfilipes.infrastructure.repository.jooq.tables.ArticleTags;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleTagsRecord extends UpdatableRecordImpl<ArticleTagsRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.article_tags.article</code>.
     */
    public void setArticle(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.article_tags.article</code>.
     */
    public UUID getArticle() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.article_tags.tag</code>.
     */
    public void setTag(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.article_tags.tag</code>.
     */
    public UUID getTag() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return ArticleTags.ARTICLE_TAGS.ARTICLE;
    }

    @Override
    public Field<UUID> field2() {
        return ArticleTags.ARTICLE_TAGS.TAG;
    }

    @Override
    public UUID component1() {
        return getArticle();
    }

    @Override
    public UUID component2() {
        return getTag();
    }

    @Override
    public UUID value1() {
        return getArticle();
    }

    @Override
    public UUID value2() {
        return getTag();
    }

    @Override
    public ArticleTagsRecord value1(UUID value) {
        setArticle(value);
        return this;
    }

    @Override
    public ArticleTagsRecord value2(UUID value) {
        setTag(value);
        return this;
    }

    @Override
    public ArticleTagsRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleTagsRecord
     */
    public ArticleTagsRecord() {
        super(ArticleTags.ARTICLE_TAGS);
    }

    /**
     * Create a detached, initialised ArticleTagsRecord
     */
    public ArticleTagsRecord(UUID article, UUID tag) {
        super(ArticleTags.ARTICLE_TAGS);

        setArticle(article);
        setTag(tag);
    }
}
