/*
 * This file is generated by jOOQ.
 */
package io.github.rogerfilipes.infrastructure.repository.jooq.tables.records;


import io.github.rogerfilipes.infrastructure.repository.jooq.tables.UserFollowings;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserFollowingsRecord extends UpdatableRecordImpl<UserFollowingsRecord> implements Record3<UUID, UUID, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_followings.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_followings.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.user_followings.follows_id</code>.
     */
    public void setFollowsId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_followings.follows_id</code>.
     */
    public UUID getFollowsId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.user_followings.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_followings.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, UUID, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return UserFollowings.USER_FOLLOWINGS.USER_ID;
    }

    @Override
    public Field<UUID> field2() {
        return UserFollowings.USER_FOLLOWINGS.FOLLOWS_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return UserFollowings.USER_FOLLOWINGS.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getUserId();
    }

    @Override
    public UUID component2() {
        return getFollowsId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getUserId();
    }

    @Override
    public UUID value2() {
        return getFollowsId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public UserFollowingsRecord value1(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserFollowingsRecord value2(UUID value) {
        setFollowsId(value);
        return this;
    }

    @Override
    public UserFollowingsRecord value3(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserFollowingsRecord values(UUID value1, UUID value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserFollowingsRecord
     */
    public UserFollowingsRecord() {
        super(UserFollowings.USER_FOLLOWINGS);
    }

    /**
     * Create a detached, initialised UserFollowingsRecord
     */
    public UserFollowingsRecord(UUID userId, UUID followsId, LocalDateTime createdAt) {
        super(UserFollowings.USER_FOLLOWINGS);

        setUserId(userId);
        setFollowsId(followsId);
        setCreatedAt(createdAt);
    }
}
