/*
 * This file is generated by jOOQ.
 */
package io.github.rogerfilipes.infrastructure.repository.jooq.tables.records;


import io.github.rogerfilipes.infrastructure.repository.jooq.tables.UserFavorites;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserFavoritesRecord extends UpdatableRecordImpl<UserFavoritesRecord> implements Record3<UUID, UUID, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_favorites.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_favorites.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.user_favorites.article</code>.
     */
    public void setArticle(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_favorites.article</code>.
     */
    public UUID getArticle() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.user_favorites.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_favorites.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, UUID, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return UserFavorites.USER_FAVORITES.USER_ID;
    }

    @Override
    public Field<UUID> field2() {
        return UserFavorites.USER_FAVORITES.ARTICLE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return UserFavorites.USER_FAVORITES.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getUserId();
    }

    @Override
    public UUID component2() {
        return getArticle();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getUserId();
    }

    @Override
    public UUID value2() {
        return getArticle();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public UserFavoritesRecord value1(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserFavoritesRecord value2(UUID value) {
        setArticle(value);
        return this;
    }

    @Override
    public UserFavoritesRecord value3(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserFavoritesRecord values(UUID value1, UUID value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserFavoritesRecord
     */
    public UserFavoritesRecord() {
        super(UserFavorites.USER_FAVORITES);
    }

    /**
     * Create a detached, initialised UserFavoritesRecord
     */
    public UserFavoritesRecord(UUID userId, UUID article, LocalDateTime createdAt) {
        super(UserFavorites.USER_FAVORITES);

        setUserId(userId);
        setArticle(article);
        setCreatedAt(createdAt);
    }
}
