/*
 * This file is generated by jOOQ.
 */
package io.github.rogerfilipes.infrastructure.repository.jooq.tables;


import io.github.rogerfilipes.infrastructure.repository.jooq.Keys;
import io.github.rogerfilipes.infrastructure.repository.jooq.Public;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.records.ArticleTagsRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleTags extends TableImpl<ArticleTagsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.article_tags</code>
     */
    public static final ArticleTags ARTICLE_TAGS = new ArticleTags();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ArticleTagsRecord> getRecordType() {
        return ArticleTagsRecord.class;
    }

    /**
     * The column <code>public.article_tags.article</code>.
     */
    public final TableField<ArticleTagsRecord, UUID> ARTICLE = createField(DSL.name("article"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.article_tags.tag</code>.
     */
    public final TableField<ArticleTagsRecord, UUID> TAG = createField(DSL.name("tag"), SQLDataType.UUID.nullable(false), this, "");

    private ArticleTags(Name alias, Table<ArticleTagsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ArticleTags(Name alias, Table<ArticleTagsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.article_tags</code> table reference
     */
    public ArticleTags(String alias) {
        this(DSL.name(alias), ARTICLE_TAGS);
    }

    /**
     * Create an aliased <code>public.article_tags</code> table reference
     */
    public ArticleTags(Name alias) {
        this(alias, ARTICLE_TAGS);
    }

    /**
     * Create a <code>public.article_tags</code> table reference
     */
    public ArticleTags() {
        this(DSL.name("article_tags"), null);
    }

    public <O extends Record> ArticleTags(Table<O> child, ForeignKey<O, ArticleTagsRecord> key) {
        super(child, key, ARTICLE_TAGS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ArticleTagsRecord> getPrimaryKey() {
        return Keys.PK_ARTICLE_TAGS;
    }

    @Override
    public List<ForeignKey<ArticleTagsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ARTICLE_TAGS__FK_ARTICLE_TAGS_ARTICLE, Keys.ARTICLE_TAGS__FK_ARTICLE_TAGS_TAGS);
    }

    private transient Articles _articles;
    private transient Tags _tags;

    /**
     * Get the implicit join path to the <code>public.articles</code> table.
     */
    public Articles articles() {
        if (_articles == null)
            _articles = new Articles(this, Keys.ARTICLE_TAGS__FK_ARTICLE_TAGS_ARTICLE);

        return _articles;
    }

    /**
     * Get the implicit join path to the <code>public.tags</code> table.
     */
    public Tags tags() {
        if (_tags == null)
            _tags = new Tags(this, Keys.ARTICLE_TAGS__FK_ARTICLE_TAGS_TAGS);

        return _tags;
    }

    @Override
    public ArticleTags as(String alias) {
        return new ArticleTags(DSL.name(alias), this);
    }

    @Override
    public ArticleTags as(Name alias) {
        return new ArticleTags(alias, this);
    }

    @Override
    public ArticleTags as(Table<?> alias) {
        return new ArticleTags(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleTags rename(String name) {
        return new ArticleTags(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleTags rename(Name name) {
        return new ArticleTags(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleTags rename(Table<?> name) {
        return new ArticleTags(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super UUID, ? super UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super UUID, ? super UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
