/*
 * This file is generated by jOOQ.
 */
package io.github.rogerfilipes.infrastructure.repository.jooq;


import io.github.rogerfilipes.infrastructure.repository.jooq.tables.ArticleTags;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.Articles;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.Comments;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.Databasechangelog;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.Databasechangeloglock;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.Tags;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.UserFavorites;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.UserFollowings;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.article_tags</code>.
     */
    public final ArticleTags ARTICLE_TAGS = ArticleTags.ARTICLE_TAGS;

    /**
     * The table <code>public.articles</code>.
     */
    public final Articles ARTICLES = Articles.ARTICLES;

    /**
     * The table <code>public.comments</code>.
     */
    public final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.tags</code>.
     */
    public final Tags TAGS = Tags.TAGS;

    /**
     * The table <code>public.user_favorites</code>.
     */
    public final UserFavorites USER_FAVORITES = UserFavorites.USER_FAVORITES;

    /**
     * The table <code>public.user_followings</code>.
     */
    public final UserFollowings USER_FOLLOWINGS = UserFollowings.USER_FOLLOWINGS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ArticleTags.ARTICLE_TAGS,
            Articles.ARTICLES,
            Comments.COMMENTS,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Tags.TAGS,
            UserFavorites.USER_FAVORITES,
            UserFollowings.USER_FOLLOWINGS,
            Users.USERS
        );
    }
}
