/*
 * This file is generated by jOOQ.
 */
package io.github.rogerfilipes.infrastructure.repository.jooq;


import io.github.rogerfilipes.infrastructure.repository.jooq.tables.ArticleTags;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.Articles;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.Comments;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.Databasechangelog;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.Databasechangeloglock;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.Tags;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.UserFavorites;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.UserFollowings;
import io.github.rogerfilipes.infrastructure.repository.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.article_tags</code>.
     */
    public static final ArticleTags ARTICLE_TAGS = ArticleTags.ARTICLE_TAGS;

    /**
     * The table <code>public.articles</code>.
     */
    public static final Articles ARTICLES = Articles.ARTICLES;

    /**
     * The table <code>public.comments</code>.
     */
    public static final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.tags</code>.
     */
    public static final Tags TAGS = Tags.TAGS;

    /**
     * The table <code>public.user_favorites</code>.
     */
    public static final UserFavorites USER_FAVORITES = UserFavorites.USER_FAVORITES;

    /**
     * The table <code>public.user_followings</code>.
     */
    public static final UserFollowings USER_FOLLOWINGS = UserFollowings.USER_FOLLOWINGS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
